name: gg_template
description: gg_template is the template project for new ggsuite projects
version: 1.0.0
repository: https://github.com/ggsuite/gg_template.git
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  path: ^1.8.0
  args: ^2.7.0
  gg_console_colors: ^2.1.5
  gg_process: ^1.1.6
  gg_args: ^2.0.4
  gg_log: ^1.0.6

dev_dependencies:
  gg_capture_print: ^1.0.9
  lints: ^5.0.0
  test: ^1.24.0

executables:
 gg_template: